/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Projects2Import } from './routes/Projects-2'
import { Route as Projects1Import } from './routes/Projects-1'
import { Route as ContactImport } from './routes/Contact'
import { Route as About2Import } from './routes/About-2'
import { Route as About1Import } from './routes/About-1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Projects2Route = Projects2Import.update({
  id: '/Projects-2',
  path: '/Projects-2',
  getParentRoute: () => rootRoute,
} as any)

const Projects1Route = Projects1Import.update({
  id: '/Projects-1',
  path: '/Projects-1',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRoute,
} as any)

const About2Route = About2Import.update({
  id: '/About-2',
  path: '/About-2',
  getParentRoute: () => rootRoute,
} as any)

const About1Route = About1Import.update({
  id: '/About-1',
  path: '/About-1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/About-1': {
      id: '/About-1'
      path: '/About-1'
      fullPath: '/About-1'
      preLoaderRoute: typeof About1Import
      parentRoute: typeof rootRoute
    }
    '/About-2': {
      id: '/About-2'
      path: '/About-2'
      fullPath: '/About-2'
      preLoaderRoute: typeof About2Import
      parentRoute: typeof rootRoute
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/Projects-1': {
      id: '/Projects-1'
      path: '/Projects-1'
      fullPath: '/Projects-1'
      preLoaderRoute: typeof Projects1Import
      parentRoute: typeof rootRoute
    }
    '/Projects-2': {
      id: '/Projects-2'
      path: '/Projects-2'
      fullPath: '/Projects-2'
      preLoaderRoute: typeof Projects2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About-1': typeof About1Route
  '/About-2': typeof About2Route
  '/Contact': typeof ContactRoute
  '/Projects-1': typeof Projects1Route
  '/Projects-2': typeof Projects2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About-1': typeof About1Route
  '/About-2': typeof About2Route
  '/Contact': typeof ContactRoute
  '/Projects-1': typeof Projects1Route
  '/Projects-2': typeof Projects2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/About-1': typeof About1Route
  '/About-2': typeof About2Route
  '/Contact': typeof ContactRoute
  '/Projects-1': typeof Projects1Route
  '/Projects-2': typeof Projects2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/About-1'
    | '/About-2'
    | '/Contact'
    | '/Projects-1'
    | '/Projects-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About-1' | '/About-2' | '/Contact' | '/Projects-1' | '/Projects-2'
  id:
    | '__root__'
    | '/'
    | '/About-1'
    | '/About-2'
    | '/Contact'
    | '/Projects-1'
    | '/Projects-2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  About1Route: typeof About1Route
  About2Route: typeof About2Route
  ContactRoute: typeof ContactRoute
  Projects1Route: typeof Projects1Route
  Projects2Route: typeof Projects2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  About1Route: About1Route,
  About2Route: About2Route,
  ContactRoute: ContactRoute,
  Projects1Route: Projects1Route,
  Projects2Route: Projects2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/About-1",
        "/About-2",
        "/Contact",
        "/Projects-1",
        "/Projects-2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/About-1": {
      "filePath": "About-1.tsx"
    },
    "/About-2": {
      "filePath": "About-2.tsx"
    },
    "/Contact": {
      "filePath": "Contact.tsx"
    },
    "/Projects-1": {
      "filePath": "Projects-1.tsx"
    },
    "/Projects-2": {
      "filePath": "Projects-2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
